In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [62]:
np.full((1,10),5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [68]:
np.repeat(5,10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [100]:
array=np.arange(0,9).reshape(3,3)

In [101]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [74]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
np.random.rand(1)

array([0.67652771])

In [76]:
N

array([ 1.14557146e+00, -1.73324377e+00, -1.40625868e-01, -3.43653097e-01,
       -1.01639303e+00,  2.53434815e+00, -1.56216069e+00,  5.20351186e-01,
        3.23839950e-02, -5.08289884e-01, -6.27459467e-02,  9.79980584e-01,
        2.02404313e+00, -6.39729598e-01, -2.59195566e-01, -3.90399392e-01,
       -7.47649081e-01, -7.97275369e-01,  6.78348278e-04, -5.92545385e-01,
       -1.11276963e+00, -9.53622542e-01, -2.55273394e-01,  4.58529579e-01,
       -1.03555811e+00])

In [77]:
N = np.random.randn(25)

In [78]:
N

array([ 1.365003  , -0.9888209 ,  2.3160496 ,  0.07549648,  0.63676976,
        0.56330834,  1.29576013, -1.06811372, -0.08640112,  0.63095958,
       -1.06391504,  0.33653313,  1.51179477, -1.55533826,  0.16721119,
       -0.44915443,  0.61231726, -0.34703585, -0.74318057,  0.99379823,
       -1.01689078, -1.23555359, -0.23596933, -0.18903153,  0.69351109])

In [79]:
L = np.linspace(0.01,1,100).reshape(10,-2)

In [80]:
L

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [81]:
 L = np.linspace(0,1,20)

In [82]:
L

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [83]:
mat = np.arange(1,26).reshape(5,5)

In [84]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [85]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [86]:
mat[3][4]

20

In [87]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [88]:
mat[4:5]

array([[21, 22, 23, 24, 25]])

In [89]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [90]:
mat.sum()

325

In [91]:
np.std(mat)

7.211102550927978

In [103]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [58]:
np.median(mat,axis=0)

array([11., 12., 13., 14., 15.])

In [104]:
array = np.arange(10,50)

In [105]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])